generate.thread_pool_size = 1
generate.only_alive_patients = true
exporter.baseDirectory = /out
exporter.years_of_history = 10
exporter.fhir.export = true
exporter.hospital.fhir.export = true
exporter.practitioner.fhir.export = true
exporter.ccda.export = false
exporter.csv.export = false
exporter.text.export = false
exporter.metadata.export = false
